#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE SCHEMA extensions;
  GRANT USAGE ON SCHEMA extensions TO public;
  GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions TO public;
  ALTER DEFAULT PRIVILEGES IN SCHEMA extensions GRANT EXECUTE ON FUNCTIONS TO public;
  ALTER DEFAULT PRIVILEGES IN SCHEMA extensions GRANT USAGE ON TYPES TO public;
  CREATE EXTENSION pg_trgm WITH SCHEMA extensions;
  CREATE EXTENSION "uuid-ossp" WITH SCHEMA extensions;

  CREATE SCHEMA "order_service";
  CREATE USER "${ORDER_SERVICE_DB_USER}" WITH PASSWORD '${ORDER_SERVICE_DB_PASSWORD}';
  GRANT CREATE, USAGE ON SCHEMA "order_service" TO "${ORDER_SERVICE_DB_USER}";
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "order_service" TO "${ORDER_SERVICE_DB_USER}";
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "order_service" TO "${ORDER_SERVICE_DB_USER}";
  ALTER DEFAULT PRIVILEGES IN SCHEMA "order_service" GRANT ALL ON TABLES TO "${ORDER_SERVICE_DB_USER}";
  ALTER DEFAULT PRIVILEGES IN SCHEMA "order_service" GRANT ALL ON SEQUENCES TO "${ORDER_SERVICE_DB_USER}";
  ALTER ROLE "${ORDER_SERVICE_DB_USER}" SET search_path TO "order_service", extensions;
  GRANT CONNECT ON DATABASE postgres TO "${ORDER_SERVICE_DB_USER}";

  CREATE SCHEMA "logistics_service";
  CREATE USER "${LOGISTICS_SERVICE_DB_USER}" WITH PASSWORD '${LOGISTICS_SERVICE_DB_PASSWORD}';
  GRANT CREATE, USAGE ON SCHEMA "logistics_service" TO "${LOGISTICS_SERVICE_DB_USER}";
  GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA "logistics_service" TO "${LOGISTICS_SERVICE_DB_USER}";
  GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA "logistics_service" TO "${LOGISTICS_SERVICE_DB_USER}";
  ALTER DEFAULT PRIVILEGES IN SCHEMA "logistics_service" GRANT ALL ON TABLES TO "${LOGISTICS_SERVICE_DB_USER}";
  ALTER DEFAULT PRIVILEGES IN SCHEMA "logistics_service" GRANT ALL ON SEQUENCES TO "${LOGISTICS_SERVICE_DB_USER}";
  ALTER ROLE "${LOGISTICS_SERVICE_DB_USER}" SET search_path TO "logistics_service", extensions;
  GRANT CONNECT ON DATABASE postgres TO "${LOGISTICS_SERVICE_DB_USER}";

  CREATE USER "grafana" WITH PASSWORD '${GRAFANA_DB_PASSWORD}';
  GRANT CONNECT ON DATABASE "postgres" TO "grafana";
  GRANT USAGE ON SCHEMA "order_service" TO "grafana";
  GRANT USAGE ON SCHEMA "logistics_service" TO "grafana";
  GRANT SELECT ON ALL TABLES IN SCHEMA "order_service" TO "grafana";
  GRANT SELECT ON ALL TABLES IN SCHEMA "logistics_service" TO "grafana";
  ALTER DEFAULT PRIVILEGES IN SCHEMA "order_service" GRANT SELECT ON TABLES TO "grafana";
  ALTER DEFAULT PRIVILEGES IN SCHEMA "logistics_service" GRANT SELECT ON TABLES TO "grafana";
  ALTER DEFAULT PRIVILEGES FOR USER "${ORDER_SERVICE_DB_USER}" IN SCHEMA "order_service" GRANT SELECT ON TABLES TO "grafana";
  ALTER DEFAULT PRIVILEGES FOR USER "${LOGISTICS_SERVICE_DB_USER}" IN SCHEMA "logistics_service" GRANT SELECT ON TABLES TO "grafana";

  CREATE USER "${CONDUKTOR_DB_USER}" WITH PASSWORD '${CONDUKTOR_DB_PASSWORD}';
  CREATE DATABASE "conduktor-console";
  GRANT ALL PRIVILEGES ON DATABASE "conduktor-console" TO "${CONDUKTOR_DB_USER}";
  \c "conduktor-console"
  GRANT ALL ON SCHEMA public TO "${CONDUKTOR_DB_USER}";
EOSQL