{
 "title": "Orders Sync – order_service vs logistics_service",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "time_bucket", "label": "Time bucket", "query": "second,minute,hour" }
  ]
 },
 "panels": [
  {
   "title": "Total orders: order-service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS value\nFROM \"order_service\".orders l"
    }
   ]
  },
  {
   "title": "Total orders: logistics-service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS value\nFROM \"logistics_service\".orders l"
    }
   ]
  },
  {
   "title": "Number of orders only in order-service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS value\nFROM \"order_service\".orders l\nLEFT JOIN \"logistics_service\".orders o\n  ON o.id = l.id\nWHERE o.id IS NULL;"
    }
   ]
  },
  {
   "title": "Orders created: order-service (per ${time_bucket})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('${time_bucket}', o.created) AS time,\n  COUNT(*) AS order_count\nFROM \"order_service\".orders o\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Orders received: logistics-service  (per ${time_bucket})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('${time_bucket}', o.created) AS time,\n  COUNT(*) AS order_count\nFROM \"logistics_service\".orders o\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Number of orders only in logistics-service",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS value\nFROM \"logistics_service\".orders l\nLEFT JOIN \"order_service\".orders o\n  ON o.id = l.id\nWHERE o.id IS NULL;"
    }
   ]
  },
  {
   "title": "Orders created only in order-service (per ${time_bucket})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('${time_bucket}', o.created) AS time,\n  COUNT(*) AS missed_orders\nFROM \"order_service\".orders o\nLEFT JOIN \"logistics_service\".orders l\n  ON l.id = o.id\nWHERE l.id IS NULL\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Orders existing only in logistics-service (per ${time_bucket})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('${time_bucket}', o.created) AS time,\n  COUNT(*) AS missed_orders\nFROM \"logistics_service\".orders o\nLEFT JOIN \"order_service\".orders l\n  ON l.id = o.id\nWHERE l.id IS NULL\nGROUP BY time\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Missed orders",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  'logistics service' as service_name,\n  count(*) as \"Number of mismatched orders\"\n FROM \"logistics_service\".orders l\nLEFT JOIN \"order_service\".orders o\n  ON o.id = l.id\nWHERE o.id IS NULL\nGROUP BY service_name\n\nUNION ALL\n\nSELECT\n  'order service' as service_name,\n  count(*) as \"Number of mismatched orders\"\n FROM \"order_service\".orders l\nLEFT JOIN \"logistics_service\".orders o\n  ON o.id = l.id\nWHERE o.id IS NULL\nGROUP BY service_name"
    }
   ]
  }
 ]
}