spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: order-service
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  sql.init.mode: never
  kafka:
    bootstrap-servers: localhost:9092
producer:
  topic: orders
server:
  port: 8078